# Config file for doomsayer_diagnostics.r
# keep_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/doomsayer_keep.txt
# drop_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/doomsayer_drop.txt
# M_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/NMF_M_spectra.txt
# M_path_rates: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/NMF_M_spectra_rates.txt
# W_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/NMF_W_sig_contribs.txt
# H_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/NMF_H_sig_loads.txt
# RMSE_path: C:/Users/jedidiah/Dropbox/Github/doomsayer/demo/output/doomsayer_rmse.txt

keep_path: doomsayer_keep.txt
drop_path: doomsayer_drop.txt
M_path: NMF_M_spectra.txt
M_path_rates: NMF_M_spectra_rates.txt
W_path: NMF_W_sig_contribs.txt
H_path: NMF_H_sig_loads.txt
RMSE_path: doomsayer_rmse.txt
